// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Access
{
    public int AccessId { get; set; }

    public string AccessName { get; set; }

    public string AccessDescription { get; set; }

    public virtual ICollection<Roles_Access> Roles_Access { get; set; } = new List<Roles_Access>();
}