// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Actors
{
    public int ActorId { get; set; }

    public string ActorName { get; set; }

    public virtual ICollection<Movie_Actor> Movie_Actor { get; set; } = new List<Movie_Actor>();
}