// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Admins_Password
{
    public string Account { get; set; }

    public string AdminPassword { get; set; }

    public virtual Admins AccountNavigation { get; set; }
}