// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Admins
{
    public string Account { get; set; }

    public int Role_Id { get; set; }

    public string AdminName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Admins_Password Admins_Password { get; set; }

    public virtual Roles Role { get; set; }
}