// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Auditoriums
{
    public int AuditoriumId { get; set; }

    public int? Theater_Id { get; set; }

    public string AuditoriumName { get; set; }

    public int TotalSeats { get; set; }

    public string AuditoriumType { get; set; }

    public virtual ICollection<Seats> Seats { get; set; } = new List<Seats>();

    public virtual ICollection<Shows> Shows { get; set; } = new List<Shows>();

    public virtual Theaters Theater { get; set; }
}