// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class BookingSeats_Detail
{
    public int DetailId { get; set; }

    public int? Booking_Id { get; set; }

    public int? ShowSeat_Id { get; set; }

    public virtual Bookings Booking { get; set; }

    public virtual ShowSeats ShowSeat { get; set; }
}