// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Comments
{
    public int CommentsId { get; set; }

    public int Movie_Id { get; set; }

    public int User_Id { get; set; }

    public string CommentMessage { get; set; }

    public DateTime? CommentTime { get; set; }

    public virtual Movies Movie { get; set; }

    public virtual Users User { get; set; }
}