// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Contacts
{
    public int ContactId { get; set; }

    public int User_Id { get; set; }

    public string IssueType { get; set; }

    public string ContactDescription { get; set; }

    public string ContactStatus { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public virtual Users User { get; set; }
}