// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Coupons
{
    public int CouponID { get; set; }

    public string CouponCode { get; set; }

    public string DiscountType { get; set; }

    public decimal DiscountValue { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly ExpiryDate { get; set; }

    public int? MaxUsageCount { get; set; }

    public int? CurrentUsageCount { get; set; }

    public string Description { get; set; }

    public int? MinimumPurchaseAmount { get; set; }

    public virtual ICollection<BookingCoupons> BookingCoupons { get; set; } = new List<BookingCoupons>();
}