// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Habbits
{
    public int HabbitId { get; set; }

    public string Habbit { get; set; }

    public virtual ICollection<User_Habbit> User_Habbit { get; set; } = new List<User_Habbit>();
}