// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Movie_Class
{
    public int Movie_Id { get; set; }

    public int Class_Id { get; set; }

    public int? Other { get; set; }

    public virtual Classes Class { get; set; }

    public virtual Movies Movie { get; set; }
}