// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Movies
{
    public int MovieId { get; set; }

    public string MovieName { get; set; }

    public string MovieEnglishName { get; set; }

    public string MovieDescription { get; set; }

    public DateOnly ReleaseDate { get; set; }

    public int Runtime { get; set; }

    public int Level { get; set; }

    public string Language { get; set; }

    public string MovieImage { get; set; }

    public string Movievideo { get; set; }

    public string DirectorName { get; set; }

    public int MovieState { get; set; }

    public virtual ICollection<Comments> Comments { get; set; } = new List<Comments>();

    public virtual ICollection<Movie_Actor> Movie_Actor { get; set; } = new List<Movie_Actor>();

    public virtual ICollection<Movie_Class> Movie_Class { get; set; } = new List<Movie_Class>();

    public virtual ICollection<Rating> Rating { get; set; } = new List<Rating>();

    public virtual ICollection<Shows> Shows { get; set; } = new List<Shows>();
}