// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Rating
{
    public int Movie_Id { get; set; }

    public int User_Id { get; set; }

    public int Rating1 { get; set; }

    public virtual Movies Movie { get; set; }

    public virtual Users User { get; set; }
}