// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Roles
{
    public int RoleId { get; set; }

    public string RoleName { get; set; }

    public string RoleDescription { get; set; }

    public virtual ICollection<Admins> Admins { get; set; } = new List<Admins>();

    public virtual ICollection<Roles_Access> Roles_Access { get; set; } = new List<Roles_Access>();
}