// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Seats
{
    public int SeatId { get; set; }

    public int? Auditorium_Id { get; set; }

    public int SeatNumber { get; set; }

    public string SeatRow { get; set; }

    public string SeatType { get; set; }

    public string SeatStatus { get; set; }

    public virtual Auditoriums Auditorium { get; set; }

    public virtual ICollection<ShowSeats> ShowSeats { get; set; } = new List<ShowSeats>();
}