// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Shows
{
    public int ShowId { get; set; }

    public int Movie_Id { get; set; }

    public int Auditorium_Id { get; set; }

    public DateTime ShowDateTime { get; set; }

    public virtual Auditoriums Auditorium { get; set; }

    public virtual ICollection<Bookings> Bookings { get; set; } = new List<Bookings>();

    public virtual Movies Movie { get; set; }

    public virtual ICollection<ShowSeats> ShowSeats { get; set; } = new List<ShowSeats>();

    public virtual ICollection<Twins> Twins { get; set; } = new List<Twins>();
}