// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class ShowSeats
{
    public int ShowSeatId { get; set; }

    public int? Show_Id { get; set; }

    public int? Seat_Id { get; set; }

    public string ShowSeatStatus { get; set; }

    public virtual ICollection<BookingSeats_Detail> BookingSeats_Detail { get; set; } = new List<BookingSeats_Detail>();

    public virtual Seats Seat { get; set; }

    public virtual Shows Show { get; set; }
}