// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Snacks
{
    public int SnackId { get; set; }

    public string SnackName { get; set; }

    public string SnackImages { get; set; }

    public int Price { get; set; }

    public virtual ICollection<BookingSnacks> BookingSnacks { get; set; } = new List<BookingSnacks>();
}