// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Theaters
{
    public int TheaterId { get; set; }

    public string TheaterName { get; set; }

    public string TheaterPhone { get; set; }

    public string TheaterEmail { get; set; }

    public string TheaterLocation { get; set; }

    public string TheaterDescription { get; set; }

    public TimeOnly TheaterStartTime { get; set; }

    public TimeOnly TheaterEndTime { get; set; }

    public string TheaterImage { get; set; }

    public virtual ICollection<Auditoriums> Auditoriums { get; set; } = new List<Auditoriums>();
}