// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class UserPasswords
{
    public int UserPasswordId { get; set; }

    public int? UserId { get; set; }

    public string Password { get; set; }

    public bool? Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Users User { get; set; }
}