// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Movie_Theater.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string NickName { get; set; }

    public DateOnly Birthday { get; set; }

    public string Phone { get; set; }

    public string Sex { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string MBTI { get; set; }

    public int? Points { get; set; }

    public string EmailToken { get; set; }

    public bool? EmailConfirm { get; set; }

    public virtual ICollection<Comments> Comments { get; set; } = new List<Comments>();

    public virtual ICollection<Contacts> Contacts { get; set; } = new List<Contacts>();

    public virtual ICollection<Rating> Rating { get; set; } = new List<Rating>();

    public virtual ICollection<Twins> TwinsInvitee { get; set; } = new List<Twins>();

    public virtual ICollection<Twins> TwinsUser { get; set; } = new List<Twins>();

    public virtual ICollection<UserPasswords> UserPasswords { get; set; } = new List<UserPasswords>();

    public virtual ICollection<User_Habbit> User_Habbit { get; set; } = new List<User_Habbit>();
}